baseURL: "https://nwj.cc/"
languageCode: "en-us"
title: "NWJ"

params:
  author: "Nick Willett-Jeffries"
  city: "New York, NY"
  email: "nwillettjeffries@gmail.com"
  description: "The personal site of Nick Willett-Jeffries."
