baseURL = "https://nwj.cc/"
languageCode = "en-us"
title = "NWJ"
theme = "nwj"

[params]
  author = "Nick Willett-Jeffries"
  city = "New York, NY"
  email = "nwillettjeffries@gmail.com"
  description = "Testing 123"
