baseURL: "https://nwj.cc/"
languageCode: "en-us"
title: "NWJ"
enableGitInfo: true
enableRobotsTXT: true

params:
  author: "Nick Willett-Jeffries"
  city: "New York, NY"
  email: "hello@nwj.cc"
  description: "The personal site of Nick Willett-Jeffries."

taxonomies:
  tag: tags
  topic: topics

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
